on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          target-branch: master

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: pnpm/action-setup@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          version: 10

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: "22"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies and Build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Check npm auth
        run: npm whoami

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --provenance
